### ISSUE TITLE
Windows compatible filenames

### ISSUE THREAD

**Issue by colbylippert** [krulllab/COSDD#1]
Colons not supported on Windows file systems

diff --git a/prediction.py b/prediction.py
index c61a397..ce257b7 100644
--- a/prediction.py
+++ b/prediction.py
@@ -112,7 +112,7 @@ if denoised.shape != original_shape:
 if not os.path.exists(cfg["data"]["save-path"]):
     print(f'Creating directory: {cfg["data"]["save-path"]}')
     os.makedirs(cfg["data"]["save-path"])
-current_time = time.strftime("%d-%m-%y-%X", time.localtime())
+current_time = time.strftime("%d-%m-%y_%H-%M-%S", time.localtime())
 save_path = os.path.join(cfg["data"]["save-path"], f"denoised-{current_time}.tif")
 print(f"Saving denoised images to {save_path}")
 tifffile.imwrite(save_path, denoised.numpy())

**Comment by Ben-Salmon** [comment]
Thanks for raising this, changed it to dashes.
